"""record vital signs for each visit

Revision ID: 385fa24ef283
Revises: f4c4d6f11560
Created: 2026-09-19 13:58:47.529357
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '385fa24ef283'
down_revision: str | None = 'f4c4d6f11560'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Who gets each permission in clinics that already exist, matching the
# defaults a new clinic is given. The staff role starts read-only there, so
# it only reads them here.
GRANTS = {
    "vitals:record": ("Take and correct vital signs", ("clinic-admin", "doctor", "receptionist")),
    "vitals:read": (
        "View vital signs",
        ("clinic-admin", "doctor", "receptionist", "staff"),
    ),
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vitals',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('queue_entry_id', sa.UUID(), nullable=False),
    sa.Column('systolic_mmhg', sa.Integer(), nullable=True),
    sa.Column('diastolic_mmhg', sa.Integer(), nullable=True),
    sa.Column('pulse_bpm', sa.Integer(), nullable=True),
    sa.Column('temperature_c', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('spo2_percent', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('glucose_mg_dl', sa.Integer(), nullable=True),
    sa.Column('glucose_timing', sa.String(length=12), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('taken_on', sa.Date(), nullable=False),
    sa.Column('taken_by_id', sa.UUID(), nullable=True),
    sa.Column('changed_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("glucose_timing IS NULL OR glucose_timing IN ('fasting', 'random', 'after_meal')", name='ck_vitals_glucose_timing_known'),
    sa.CheckConstraint('(glucose_mg_dl IS NULL) = (glucose_timing IS NULL)', name='ck_vitals_glucose_timing'),
    sa.CheckConstraint('(systolic_mmhg IS NULL) = (diastolic_mmhg IS NULL)', name='ck_vitals_pressure_pair'),
    sa.CheckConstraint('diastolic_mmhg IS NULL OR diastolic_mmhg BETWEEN 20 AND 200', name='ck_vitals_diastolic_mmhg'),
    sa.CheckConstraint('glucose_mg_dl IS NULL OR glucose_mg_dl BETWEEN 10 AND 1000', name='ck_vitals_glucose_mg_dl'),
    sa.CheckConstraint('height_cm IS NULL OR height_cm BETWEEN 20 AND 250', name='ck_vitals_height_cm'),
    sa.CheckConstraint('pulse_bpm IS NULL OR pulse_bpm BETWEEN 20 AND 250', name='ck_vitals_pulse_bpm'),
    sa.CheckConstraint('respiratory_rate IS NULL OR respiratory_rate BETWEEN 4 AND 80', name='ck_vitals_respiratory_rate'),
    sa.CheckConstraint('spo2_percent IS NULL OR spo2_percent BETWEEN 50 AND 100', name='ck_vitals_spo2_percent'),
    sa.CheckConstraint('systolic_mmhg IS NOT NULL OR diastolic_mmhg IS NOT NULL OR pulse_bpm IS NOT NULL OR temperature_c IS NOT NULL OR spo2_percent IS NOT NULL OR respiratory_rate IS NOT NULL OR weight_kg IS NOT NULL OR height_cm IS NOT NULL OR glucose_mg_dl IS NOT NULL', name='ck_vitals_something_measured'),
    sa.CheckConstraint('systolic_mmhg IS NULL OR diastolic_mmhg < systolic_mmhg', name='ck_vitals_pressure_order'),
    sa.CheckConstraint('systolic_mmhg IS NULL OR systolic_mmhg BETWEEN 50 AND 300', name='ck_vitals_systolic_mmhg'),
    sa.CheckConstraint('temperature_c IS NULL OR temperature_c BETWEEN 30 AND 45', name='ck_vitals_temperature_c'),
    sa.CheckConstraint('weight_kg IS NULL OR weight_kg BETWEEN 0.3 AND 400', name='ck_vitals_weight_kg'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_entry_id'], ['opd_queue_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taken_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('queue_entry_id', name='uq_vitals_queue_entry')
    )
    op.create_index(op.f('ix_vitals_organization_id'), 'vitals', ['organization_id'], unique=False)
    op.create_index('ix_vitals_patient', 'vitals', ['organization_id', 'patient_id', 'taken_at'], unique=False)
    # ### end Alembic commands ###

    # Roles are copied from the defaults when a clinic is created, so one
    # made before today would otherwise never be given these. It reaches a
    # signed-in person when their access token is next reissued.
    for code, (description, roles) in GRANTS.items():
        op.execute(
            f"""
            INSERT INTO permissions (id, code, description)
            VALUES (gen_random_uuid(), '{code}', '{description}')
            ON CONFLICT (code) DO NOTHING
            """
        )
        slugs = ", ".join(f"'{slug}'" for slug in roles)
        op.execute(
            f"""
            INSERT INTO role_permissions (id, role_id, permission_id)
            SELECT gen_random_uuid(), roles.id, permissions.id
            FROM roles
            CROSS JOIN permissions
            WHERE permissions.code = '{code}' AND roles.slug IN ({slugs})
            ON CONFLICT ON CONSTRAINT uq_role_permissions_pair DO NOTHING
            """
        )


def downgrade() -> None:
    for code in GRANTS:
        op.execute(
            f"""
            DELETE FROM role_permissions
            USING permissions
            WHERE role_permissions.permission_id = permissions.id
              AND permissions.code = '{code}'
            """
        )
        op.execute(f"DELETE FROM permissions WHERE code = '{code}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vitals_patient', table_name='vitals')
    op.drop_index(op.f('ix_vitals_organization_id'), table_name='vitals')
    op.drop_table('vitals')
    # ### end Alembic commands ###
