"""add doctors, their weekly hours and their leave

Revision ID: 38c8205b960e
Revises: e19aabc53614
Created: 2026-09-17 21:29:03.785700
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '38c8205b960e'
down_revision: str | None = 'e19aabc53614'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=8), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('speciality', sa.String(length=80), nullable=True),
    sa.Column('qualifications', sa.String(length=160), nullable=True),
    sa.Column('registration_number', sa.String(length=48), nullable=True),
    sa.Column('years_of_experience', sa.SmallInteger(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('room', sa.String(length=32), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('consultation_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('follow_up_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doctors_name_trgm', 'doctors', [sa.literal_column("lower(first_name || ' ' || last_name) gin_trgm_ops")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_doctors_organization_id'), 'doctors', ['organization_id'], unique=False)
    op.create_index('ix_doctors_status_name', 'doctors', ['organization_id', 'status', 'last_name'], unique=False)
    op.create_index('uq_doctors_registration', 'doctors', ['organization_id', sa.literal_column('lower(registration_number)')], unique=True, postgresql_where=sa.text('registration_number IS NOT NULL'))
    op.create_index('uq_doctors_user', 'doctors', ['organization_id', 'user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('doctor_leaves',
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('recorded_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('(start_time IS NULL) = (end_time IS NULL)', name='ck_doctor_leaves_time_pair'),
    sa.CheckConstraint('end_time IS NULL OR end_time > start_time', name='ck_doctor_leaves_time_order'),
    sa.CheckConstraint('ends_on >= starts_on', name='ck_doctor_leaves_order'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_leaves_organization_id'), 'doctor_leaves', ['organization_id'], unique=False)
    op.create_index('ix_doctor_leaves_span', 'doctor_leaves', ['organization_id', 'doctor_id', 'starts_on', 'ends_on'], unique=False)
    op.create_table('doctor_schedules',
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('break_start', sa.Time(), nullable=True),
    sa.Column('break_end', sa.Time(), nullable=True),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('(break_start IS NULL) = (break_end IS NULL)', name='ck_doctor_schedules_break_pair'),
    sa.CheckConstraint('break_end IS NULL OR break_end > break_start', name='ck_doctor_schedules_break_order'),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='ck_doctor_schedules_day_of_week'),
    sa.CheckConstraint('end_time > start_time', name='ck_doctor_schedules_order'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doctor_schedules_doctor', 'doctor_schedules', ['organization_id', 'doctor_id', 'day_of_week'], unique=False)
    op.create_index(op.f('ix_doctor_schedules_organization_id'), 'doctor_schedules', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_schedules_organization_id'), table_name='doctor_schedules')
    op.drop_index('ix_doctor_schedules_doctor', table_name='doctor_schedules')
    op.drop_table('doctor_schedules')
    op.drop_index('ix_doctor_leaves_span', table_name='doctor_leaves')
    op.drop_index(op.f('ix_doctor_leaves_organization_id'), table_name='doctor_leaves')
    op.drop_table('doctor_leaves')
    op.drop_index('uq_doctors_user', table_name='doctors', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('uq_doctors_registration', table_name='doctors', postgresql_where=sa.text('registration_number IS NOT NULL'))
    op.drop_index('ix_doctors_status_name', table_name='doctors')
    op.drop_index(op.f('ix_doctors_organization_id'), table_name='doctors')
    op.drop_index('ix_doctors_name_trgm', table_name='doctors', postgresql_using='gin')
    op.drop_table('doctors')
    # ### end Alembic commands ###
