"""raise bills and take payments against them

Revision ID: 3cd9da72b11b
Revises: 9309eb53f892
Created: 2026-09-21 18:51:08.122827
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3cd9da72b11b"
down_revision: str | None = "9309eb53f892"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoices",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("queue_entry_id", sa.UUID(), nullable=True),
        sa.Column("doctor_id", sa.UUID(), nullable=True),
        sa.Column("invoice_number", sa.String(length=24), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("discount_reason", sa.String(length=200), nullable=True),
        sa.Column("tax_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("amount_paid", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("refunded_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("balance", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issued_by_id", sa.UUID(), nullable=True),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("voided_by_id", sa.UUID(), nullable=True),
        sa.Column("void_reason", sa.String(length=200), nullable=True),
        sa.Column("request_key", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "(status = 'draft') = (invoice_number IS NULL)", name="ck_invoice_number"
        ),
        sa.CheckConstraint(
            "(status = 'draft') = (issued_at IS NULL)", name="ck_invoice_issued_at"
        ),
        sa.CheckConstraint(
            "(status = 'void') = (voided_at IS NOT NULL)", name="ck_invoice_void"
        ),
        sa.CheckConstraint(
            "status <> 'draft' OR amount_paid = 0", name="ck_invoice_draft_unpaid"
        ),
        sa.CheckConstraint("status <> 'paid' OR balance = 0", name="ck_invoice_paid"),
        sa.CheckConstraint(
            "status <> 'void' OR amount_paid = refunded_amount", name="ck_invoice_void_settled"
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'unpaid', 'partly_paid', 'paid', 'refunded', 'void')",
            name="ck_invoice_status",
        ),
        sa.CheckConstraint(
            "amount_paid >= 0 AND amount_paid <= total", name="ck_invoice_amount_paid"
        ),
        sa.CheckConstraint("balance = total - amount_paid", name="ck_invoice_balance"),
        sa.CheckConstraint(
            "discount_amount >= 0 AND discount_amount <= subtotal", name="ck_invoice_discount"
        ),
        sa.CheckConstraint(
            "refunded_amount >= 0 AND refunded_amount <= amount_paid",
            name="ck_invoice_refunded",
        ),
        sa.CheckConstraint("tax_amount >= 0", name="ck_invoice_tax"),
        sa.CheckConstraint(
            "tax_percent >= 0 AND tax_percent <= 100", name="ck_invoice_tax_percent"
        ),
        sa.CheckConstraint(
            "total = subtotal - discount_amount + tax_amount", name="ck_invoice_total"
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["doctor_id"], ["doctors.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["issued_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["queue_entry_id"], ["opd_queue_entries.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["voided_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_invoice_doctor",
        "invoices",
        ["organization_id", "doctor_id", "issued_at"],
        unique=False,
    )
    op.create_index(
        "ix_invoice_owed",
        "invoices",
        ["organization_id", "issued_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('unpaid', 'partly_paid')"),
    )
    op.create_index(
        "ix_invoice_patient",
        "invoices",
        ["organization_id", "patient_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_invoice_status",
        "invoices",
        ["organization_id", "status", "issued_at"],
        unique=False,
    )
    op.create_index("ix_invoice_visit", "invoices", ["queue_entry_id"], unique=False)
    op.create_index(
        op.f("ix_invoices_organization_id"), "invoices", ["organization_id"], unique=False
    )
    op.create_index(
        "uq_invoice_number", "invoices", ["organization_id", "invoice_number"], unique=True
    )
    op.create_index(
        "uq_invoice_request",
        "invoices",
        ["organization_id", "request_key"],
        unique=True,
        postgresql_where=sa.text("request_key IS NOT NULL"),
    )
    op.create_index(
        "uq_invoice_visit",
        "invoices",
        ["queue_entry_id"],
        unique=True,
        postgresql_where=sa.text("queue_entry_id IS NOT NULL AND status <> 'void'"),
    )
    op.create_table(
        "invoice_items",
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("item_type", sa.String(length=16), nullable=False),
        sa.Column("description", sa.String(length=120), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "item_type IN ('consultation', 'procedure', 'lab', 'medicine', 'other')",
            name="ck_invoice_item_type",
        ),
        sa.CheckConstraint("amount = quantity * unit_price", name="ck_invoice_item_amount"),
        sa.CheckConstraint("quantity BETWEEN 1 AND 999", name="ck_invoice_item_quantity"),
        sa.CheckConstraint("unit_price >= 0", name="ck_invoice_item_price"),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_invoice_item_invoice", "invoice_items", ["invoice_id", "position"], unique=False
    )
    op.create_index(
        op.f("ix_invoice_items_organization_id"),
        "invoice_items",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "payments",
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("reference", sa.String(length=60), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_by_id", sa.UUID(), nullable=True),
        sa.Column("request_key", sa.String(length=64), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "kind <> 'refund' OR note IS NOT NULL", name="ck_payment_refund_reason"
        ),
        sa.CheckConstraint("kind IN ('payment', 'refund')", name="ck_payment_kind"),
        sa.CheckConstraint(
            "method IN ('cash', 'upi', 'card', 'bank_transfer', 'cheque', 'other')",
            name="ck_payment_method",
        ),
        sa.CheckConstraint("amount > 0", name="ck_payment_amount"),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["received_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_payment_day", "payments", ["organization_id", "received_at"], unique=False
    )
    op.create_index(
        "ix_payment_invoice", "payments", ["invoice_id", "received_at"], unique=False
    )
    op.create_index(
        op.f("ix_payments_organization_id"), "payments", ["organization_id"], unique=False
    )
    op.create_index(
        "uq_payment_request",
        "payments",
        ["organization_id", "request_key"],
        unique=True,
        postgresql_where=sa.text("request_key IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_payment_request",
        table_name="payments",
        postgresql_where=sa.text("request_key IS NOT NULL"),
    )
    op.drop_index(op.f("ix_payments_organization_id"), table_name="payments")
    op.drop_index("ix_payment_invoice", table_name="payments")
    op.drop_index("ix_payment_day", table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_invoice_items_organization_id"), table_name="invoice_items")
    op.drop_index("ix_invoice_item_invoice", table_name="invoice_items")
    op.drop_table("invoice_items")
    op.drop_index(
        "uq_invoice_visit",
        table_name="invoices",
        postgresql_where=sa.text("queue_entry_id IS NOT NULL AND status <> 'void'"),
    )
    op.drop_index(
        "uq_invoice_request",
        table_name="invoices",
        postgresql_where=sa.text("request_key IS NOT NULL"),
    )
    op.drop_index("uq_invoice_number", table_name="invoices")
    op.drop_index(op.f("ix_invoices_organization_id"), table_name="invoices")
    op.drop_index("ix_invoice_visit", table_name="invoices")
    op.drop_index("ix_invoice_status", table_name="invoices")
    op.drop_index("ix_invoice_patient", table_name="invoices")
    op.drop_index(
        "ix_invoice_owed",
        table_name="invoices",
        postgresql_where=sa.text("status IN ('unpaid', 'partly_paid')"),
    )
    op.drop_index("ix_invoice_doctor", table_name="invoices")
    op.drop_table("invoices")
    # ### end Alembic commands ###
