"""keep files on the patient record

Revision ID: 9309eb53f892
Revises: 6edd2d9c5599
Created: 2026-09-21 12:43:17.318071
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9309eb53f892"
down_revision: str | None = "6edd2d9c5599"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patient_documents",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("consultation_id", sa.UUID(), nullable=True),
        sa.Column("lab_order_id", sa.UUID(), nullable=True),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("dated", sa.Date(), nullable=True),
        sa.Column("original_name", sa.String(length=200), nullable=False),
        sa.Column("content_type", sa.String(length=40), nullable=False),
        sa.Column("declared_type", sa.String(length=100), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("blob_url", sa.String(length=500), nullable=False),
        sa.Column("uploaded_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "category IN ('lab_report', 'scan', 'prescription', 'referral', 'discharge', 'insurance', 'other')",
            name="ck_document_category",
        ),
        sa.CheckConstraint(
            "content_type IN ('application/pdf', 'image/jpeg', 'image/png', 'image/webp')",
            name="ck_document_content_type",
        ),
        sa.CheckConstraint(
            "lab_order_id IS NULL OR category = 'lab_report'", name="ck_document_lab_category"
        ),
        sa.CheckConstraint("size_bytes > 0", name="ck_document_size"),
        sa.ForeignKeyConstraint(["consultation_id"], ["consultations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["lab_order_id"], ["lab_orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploaded_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_document_lab_order", "patient_documents", ["lab_order_id"], unique=False
    )
    op.create_index(
        "ix_document_patient",
        "patient_documents",
        ["organization_id", "patient_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_document_visit", "patient_documents", ["consultation_id"], unique=False)
    op.create_index(
        op.f("ix_patient_documents_organization_id"),
        "patient_documents",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "uq_document_per_patient", "patient_documents", ["patient_id", "sha256"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_document_per_patient", table_name="patient_documents")
    op.drop_index(op.f("ix_patient_documents_organization_id"), table_name="patient_documents")
    op.drop_index("ix_document_visit", table_name="patient_documents")
    op.drop_index("ix_document_patient", table_name="patient_documents")
    op.drop_index("ix_document_lab_order", table_name="patient_documents")
    op.drop_table("patient_documents")
    # ### end Alembic commands ###
