"""keep the doctor's notes for each visit

Revision ID: a486f4d1d786
Revises: f602e2b76ab2
Created: 2026-09-18 17:46:38.236090
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'a486f4d1d786'
down_revision: str | None = 'f602e2b76ab2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultations',
    sa.Column('queue_entry_id', sa.UUID(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('chief_complaint', sa.String(length=500), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('examination', sa.Text(), nullable=True),
    sa.Column('advice', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('written_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("(status = 'completed') = (completed_at IS NOT NULL)", name='ck_consultation_completed_at'),
    sa.CheckConstraint("status IN ('draft', 'completed')", name='ck_consultation_status'),
    sa.CheckConstraint('version > 0', name='ck_consultation_version'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_entry_id'], ['opd_queue_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['written_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consultation_doctor', 'consultations', ['organization_id', 'doctor_id', 'status', 'started_at'], unique=False)
    op.create_index('ix_consultation_patient', 'consultations', ['organization_id', 'patient_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_consultations_organization_id'), 'consultations', ['organization_id'], unique=False)
    op.create_index('uq_consultation_queue_entry', 'consultations', ['queue_entry_id'], unique=True, postgresql_where=sa.text('queue_entry_id IS NOT NULL'))
    op.create_table('consultation_addenda',
    sa.Column('consultation_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('written_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['written_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_addenda_organization_id'), 'consultation_addenda', ['organization_id'], unique=False)
    op.create_index('ix_consultation_addendum', 'consultation_addenda', ['consultation_id', 'created_at'], unique=False)
    op.create_table('consultation_diagnoses',
    sa.Column('consultation_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_diagnoses_organization_id'), 'consultation_diagnoses', ['organization_id'], unique=False)
    op.create_index('ix_consultation_diagnosis_order', 'consultation_diagnoses', ['consultation_id', 'position'], unique=False)
    op.create_index('uq_consultation_primary_diagnosis', 'consultation_diagnoses', ['consultation_id'], unique=True, postgresql_where=sa.text('is_primary'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_consultation_primary_diagnosis', table_name='consultation_diagnoses', postgresql_where=sa.text('is_primary'))
    op.drop_index('ix_consultation_diagnosis_order', table_name='consultation_diagnoses')
    op.drop_index(op.f('ix_consultation_diagnoses_organization_id'), table_name='consultation_diagnoses')
    op.drop_table('consultation_diagnoses')
    op.drop_index('ix_consultation_addendum', table_name='consultation_addenda')
    op.drop_index(op.f('ix_consultation_addenda_organization_id'), table_name='consultation_addenda')
    op.drop_table('consultation_addenda')
    op.drop_index('uq_consultation_queue_entry', table_name='consultations', postgresql_where=sa.text('queue_entry_id IS NOT NULL'))
    op.drop_index(op.f('ix_consultations_organization_id'), table_name='consultations')
    op.drop_index('ix_consultation_patient', table_name='consultations')
    op.drop_index('ix_consultation_doctor', table_name='consultations')
    op.drop_table('consultations')
    # ### end Alembic commands ###
