"""add patient records

Revision ID: e19aabc53614
Revises: f7a9df5762ea
Created: 2026-09-17 17:47:49.016308
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'e19aabc53614'
down_revision: str | None = 'f7a9df5762ea'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_counters',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('counter', sa.String(length=24), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'counter')
    )
    op.create_table('patients',
    sa.Column('patient_number', sa.String(length=24), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('preferred_name', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('alternate_phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('blood_group', sa.String(length=8), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('emergency_contact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patients_name_trgm', 'patients', [sa.literal_column("lower(first_name || ' ' || last_name) gin_trgm_ops")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_patients_organization_id'), 'patients', ['organization_id'], unique=False)
    op.create_index('ix_patients_phone', 'patients', ['organization_id', 'phone'], unique=False)
    op.create_index('ix_patients_status_name', 'patients', ['organization_id', 'status', 'last_name'], unique=False)
    op.create_index('uq_patients_number', 'patients', ['organization_id', 'patient_number'], unique=True)
    op.create_table('patient_allergies',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('substance', sa.String(length=120), nullable=False),
    sa.Column('reaction', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('recorded_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_allergies_organization_id'), 'patient_allergies', ['organization_id'], unique=False)
    op.create_index('ix_patient_allergies_patient', 'patient_allergies', ['organization_id', 'patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_patient_allergies_patient', table_name='patient_allergies')
    op.drop_index(op.f('ix_patient_allergies_organization_id'), table_name='patient_allergies')
    op.drop_table('patient_allergies')
    op.drop_index('uq_patients_number', table_name='patients')
    op.drop_index('ix_patients_status_name', table_name='patients')
    op.drop_index('ix_patients_phone', table_name='patients')
    op.drop_index(op.f('ix_patients_organization_id'), table_name='patients')
    op.drop_index('ix_patients_name_trgm', table_name='patients', postgresql_using='gin')
    op.drop_table('patients')
    op.drop_table('tenant_counters')
    # ### end Alembic commands ###
