"""add appointments and their history

Revision ID: ea275e98acf9
Revises: 4b21c7d9e0a5
Created: 2026-09-18 11:22:48.260904
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'ea275e98acf9'
down_revision: str | None = '4b21c7d9e0a5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('appointment_type', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancelled_reason', sa.String(length=200), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_id', sa.UUID(), nullable=True),
    sa.Column('booked_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    postgresql.ExcludeConstraint((sa.text('doctor_id'), '='), (sa.text('tstzrange(scheduled_start, scheduled_end)'), '&&'), where=sa.text("status NOT IN ('cancelled', 'no_show')"), using='gist', name='ex_appointments_doctor_overlap'),
    postgresql.ExcludeConstraint((sa.text('patient_id'), '='), (sa.text('tstzrange(scheduled_start, scheduled_end)'), '&&'), where=sa.text("status NOT IN ('cancelled', 'no_show')"), using='gist', name='ex_appointments_patient_overlap'),
    sa.CheckConstraint("appointment_type IN ('consultation', 'follow_up')", name='ck_appointments_type'),
    sa.CheckConstraint("source IN ('phone', 'desk')", name='ck_appointments_source'),
    sa.CheckConstraint("status IN ('scheduled', 'confirmed', 'checked_in', 'waiting', 'in_consultation', 'completed', 'cancelled', 'no_show')", name='ck_appointments_status'),
    sa.CheckConstraint('scheduled_end > scheduled_start', name='ck_appointments_order'),
    sa.ForeignKeyConstraint(['booked_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointments_doctor_start', 'appointments', ['organization_id', 'doctor_id', 'scheduled_start'], unique=False)
    op.create_index('ix_appointments_open_start', 'appointments', ['organization_id', 'scheduled_start'], unique=False, postgresql_where=sa.text("status NOT IN ('cancelled', 'no_show', 'completed')"))
    op.create_index(op.f('ix_appointments_organization_id'), 'appointments', ['organization_id'], unique=False)
    op.create_index('ix_appointments_patient_start', 'appointments', ['organization_id', 'patient_id', 'scheduled_start'], unique=False)
    op.create_table('appointment_status_history',
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=16), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("event IN ('booked', 'confirmed', 'rescheduled', 'cancelled', 'no_show', 'edited')", name='ck_appointment_history_event'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointment_history_appointment', 'appointment_status_history', ['organization_id', 'appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_status_history_organization_id'), 'appointment_status_history', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_status_history_organization_id'), table_name='appointment_status_history')
    op.drop_index('ix_appointment_history_appointment', table_name='appointment_status_history')
    op.drop_table('appointment_status_history')
    op.drop_index('ix_appointments_patient_start', table_name='appointments')
    op.drop_index(op.f('ix_appointments_organization_id'), table_name='appointments')
    op.drop_index('ix_appointments_open_start', table_name='appointments', postgresql_where=sa.text("status NOT IN ('cancelled', 'no_show', 'completed')"))
    op.drop_index('ix_appointments_doctor_start', table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
