"""add prescriptions and the list of medicines they are written from

Revision ID: f4c4d6f11560
Revises: a486f4d1d786
Created: 2026-09-19 00:46:33.827045
"""

from __future__ import annotations

import json
from collections.abc import Sequence
from pathlib import Path

import sqlalchemy as sa
from alembic import op
from uuid6 import uuid7

revision: str = 'f4c4d6f11560'
down_revision: str | None = 'a486f4d1d786'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The published list, as it was read out of the PDF and checked by hand.
_LIST = Path(__file__).resolve().parents[2] / "app" / "data" / "medicines-nlem-2022.json"


def _load_medicines() -> None:
    listed = json.loads(_LIST.read_text(encoding="utf-8"))["medicines"]
    medicines = sa.table(
        "medicines",
        sa.column("id", sa.UUID()),
        sa.column("name", sa.String()),
        sa.column("presentation", sa.String()),
        sa.column("source", sa.String()),
    )
    rows = []
    for medicine in listed:
        for presentation in medicine["presentations"] or [None]:
            rows.append(
                {
                    "id": uuid7(),
                    "name": medicine["name"],
                    "presentation": presentation,
                    "source": "nlem-2022",
                }
            )
    op.bulk_insert(medicines, rows)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('presentation', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_medicines_name_trgm', 'medicines', [sa.literal_column('lower(name) gin_trgm_ops')], unique=False, postgresql_using='gin')
    op.create_index('uq_medicine_presentation', 'medicines', [sa.literal_column('lower(name)'), sa.literal_column("coalesce(lower(presentation), '')")], unique=True)
    op.create_table('prescriptions',
    sa.Column('consultation_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('prescription_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('replaces_id', sa.UUID(), nullable=True),
    sa.Column('correction_reason', sa.String(length=200), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("(status = 'draft') = (issued_at IS NULL)", name='ck_prescription_issued_at'),
    sa.CheckConstraint("(status = 'draft') = (prescription_number IS NULL)", name='ck_prescription_numbered_once_issued'),
    sa.CheckConstraint("status IN ('draft', 'issued', 'replaced')", name='ck_prescription_status'),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replaces_id'], ['prescriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prescription_patient', 'prescriptions', ['organization_id', 'patient_id', 'issued_at'], unique=False)
    op.create_index(op.f('ix_prescriptions_organization_id'), 'prescriptions', ['organization_id'], unique=False)
    op.create_index('uq_prescription_draft', 'prescriptions', ['consultation_id'], unique=True, postgresql_where=sa.text("status = 'draft'"))
    op.create_index('uq_prescription_issued', 'prescriptions', ['consultation_id'], unique=True, postgresql_where=sa.text("status = 'issued'"))
    op.create_index('uq_prescription_number', 'prescriptions', ['organization_id', 'prescription_number'], unique=True, postgresql_where=sa.text('prescription_number IS NOT NULL'))
    op.create_table('prescription_items',
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('medicine_name', sa.String(length=200), nullable=False),
    sa.Column('presentation', sa.String(length=200), nullable=True),
    sa.Column('dose', sa.String(length=40), nullable=True),
    sa.Column('timing', sa.String(length=16), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.String(length=200), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("timing IS NULL OR timing IN ('before_food', 'after_food', 'with_food', 'empty_stomach', 'bedtime', 'as_needed')", name='ck_prescription_timing'),
    sa.CheckConstraint('duration_days IS NULL OR duration_days BETWEEN 1 AND 365', name='ck_prescription_duration'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prescription_item_name', 'prescription_items', ['organization_id', sa.literal_column('lower(medicine_name)')], unique=False)
    op.create_index('ix_prescription_item_order', 'prescription_items', ['prescription_id', 'position'], unique=False)
    op.create_index(op.f('ix_prescription_items_organization_id'), 'prescription_items', ['organization_id'], unique=False)
    # ### end Alembic commands ###
    _load_medicines()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescription_items_organization_id'), table_name='prescription_items')
    op.drop_index('ix_prescription_item_order', table_name='prescription_items')
    op.drop_index('ix_prescription_item_name', table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index('uq_prescription_number', table_name='prescriptions', postgresql_where=sa.text('prescription_number IS NOT NULL'))
    op.drop_index('uq_prescription_issued', table_name='prescriptions', postgresql_where=sa.text("status = 'issued'"))
    op.drop_index('uq_prescription_draft', table_name='prescriptions', postgresql_where=sa.text("status = 'draft'"))
    op.drop_index(op.f('ix_prescriptions_organization_id'), table_name='prescriptions')
    op.drop_index('ix_prescription_patient', table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index('uq_medicine_presentation', table_name='medicines')
    op.drop_index('ix_medicines_name_trgm', table_name='medicines', postgresql_using='gin')
    op.drop_table('medicines')
    # ### end Alembic commands ###
