"""add the day's queue

Revision ID: f602e2b76ab2
Revises: ea275e98acf9
Created: 2026-09-18 12:58:25.255598
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f602e2b76ab2'
down_revision: str | None = 'ea275e98acf9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_HISTORY_CHECK = "ck_appointment_history_event"
_BEFORE = ("booked", "confirmed", "rescheduled", "cancelled", "no_show", "edited")
_AFTER = (*_BEFORE, "checked_in", "check_in_undone", "started", "seen", "left")


def _events(values: tuple[str, ...]) -> str:
    return "event IN (" + ", ".join(f"'{value}'" for value in values) + ")"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opd_queue_entries',
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('token_date', sa.Date(), nullable=False),
    sa.Column('token_number', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("priority IN ('normal', 'urgent')", name='ck_queue_priority'),
    sa.CheckConstraint("status IN ('waiting', 'called', 'in_consultation', 'completed', 'skipped', 'no_show')", name='ck_queue_status'),
    sa.CheckConstraint('token_number > 0', name='ck_queue_token'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['checked_in_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'doctor_id', 'token_date', 'token_number', name='uq_queue_token')
    )
    op.create_index(op.f('ix_opd_queue_entries_organization_id'), 'opd_queue_entries', ['organization_id'], unique=False)
    op.create_index('ix_queue_doctor_day', 'opd_queue_entries', ['organization_id', 'doctor_id', 'token_date', 'status'], unique=False)
    op.create_index('uq_queue_appointment', 'opd_queue_entries', ['appointment_id'], unique=True, postgresql_where=sa.text('appointment_id IS NOT NULL'))
    op.create_index('uq_queue_doctor_called', 'opd_queue_entries', ['organization_id', 'doctor_id', 'token_date'], unique=True, postgresql_where=sa.text("status = 'called'"))
    op.create_index('uq_queue_doctor_in_room', 'opd_queue_entries', ['organization_id', 'doctor_id', 'token_date'], unique=True, postgresql_where=sa.text("status = 'in_consultation'"))
    op.create_index('uq_queue_patient_live', 'opd_queue_entries', ['organization_id', 'patient_id', 'token_date'], unique=True, postgresql_where=sa.text("status IN ('waiting', 'called', 'in_consultation', 'skipped')"))
    # ### end Alembic commands ###

    # The queue writes its steps into each appointment's history.
    op.drop_constraint(_HISTORY_CHECK, "appointment_status_history", type_="check")
    op.create_check_constraint(_HISTORY_CHECK, "appointment_status_history", _events(_AFTER))


def downgrade() -> None:
    added = ", ".join(f"'{value}'" for value in _AFTER if value not in _BEFORE)
    op.execute(f"DELETE FROM appointment_status_history WHERE event IN ({added})")
    op.drop_constraint(_HISTORY_CHECK, "appointment_status_history", type_="check")
    op.create_check_constraint(_HISTORY_CHECK, "appointment_status_history", _events(_BEFORE))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_queue_patient_live', table_name='opd_queue_entries', postgresql_where=sa.text("status IN ('waiting', 'called', 'in_consultation', 'skipped')"))
    op.drop_index('uq_queue_doctor_in_room', table_name='opd_queue_entries', postgresql_where=sa.text("status = 'in_consultation'"))
    op.drop_index('uq_queue_doctor_called', table_name='opd_queue_entries', postgresql_where=sa.text("status = 'called'"))
    op.drop_index('uq_queue_appointment', table_name='opd_queue_entries', postgresql_where=sa.text('appointment_id IS NOT NULL'))
    op.drop_index('ix_queue_doctor_day', table_name='opd_queue_entries')
    op.drop_index(op.f('ix_opd_queue_entries_organization_id'), table_name='opd_queue_entries')
    op.drop_table('opd_queue_entries')
    # ### end Alembic commands ###
