"""carry the invited person's name on the invitation

Revision ID: f7a9df5762ea
Revises: 9a5c043357fc
Created: 2026-09-17 14:06:25.289039
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f7a9df5762ea'
down_revision: str | None = '9a5c043357fc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('first_name', sa.String(length=80), nullable=False))
    op.add_column('invitations', sa.Column('last_name', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'last_name')
    op.drop_column('invitations', 'first_name')
    # ### end Alembic commands ###
